#baseurl = "localhost"
baseurl = "https://www.softwareascraft.com/"
title = "Software As Craft"
languageCode = "en-us"
theme = "beautifulhugo"
paginate = 10
publishDir = "docs"
keywords = ""
subtitle = "Thoughts how we build software, and the effects on our industry."
readOtherPosts = "Read other posts"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[Params]
author.name = "Paige"
author.website = "https://www.softwareascraft.com"
author.email = "paige.watson@softwareascraft.com"
author.github = "MyTurnyet"
author.twitter = "PaigeisXP"
author.linkedin = "paige-is-xp"
#youtube = "user/username" # or channel/channelname
#mastodon = "url"
logo.path = "img/paige.jpg"
logo.alt = "Software As Craft"

dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

mainSections = ["post","posts"]
favicon = "img/favicon.ico"
dateFormat = "January 2, 2006"
commit = false
rss = true
comments = true
readingTime = true
wordCount = true
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true

# Subtitle for home
subtitle = "Thoughts how we build software, and the effects on our industry."

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = true

# Metadata mostly used in document's head
description = "Thoughts how we build software, and the effects on our industry."
keywords = "homepage, blog"
images = ["img"]

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[languages]
#[languages.en]
[languages.en.params]

[languages.en.params.logo]
#logoText = "Software As Craft"
#logoHomeLink = "/"
# or
#

#alt = "Software As Craft"

# And you can even create generic menu
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts"

